### ISSUE TITLE
Viewer for custom tiles

### ISSUE THREAD

**Issue by daliborjanak** [klokantech/ol3#1]
We need to create simple viewer for new custom metadata implementation. MapTiler now generates new metadata for custom tiles with tilematrix (since 0.6.4). Specified in: https://github.com/klokan/maptiler/issues/268#issuecomment-188742237

Custom projection metadata rendered with tiles:
http://labs.klokantech.com/tileserver/cr/metadata.json
http://labs.klokantech.com/tileserver/swiss/metadata.json
http://labs.klokantech.com/tileserver/usa/metadata.json
http://labs.klokantech.com/tileserver/france/metadata.json
...
You can see it directly in labs ftp or render with new maptiler PRO
All layes on server accessible through tileserver-php:
http://labs.klokantech.com/tileserver/

We can add it as tilejson to OL3 or load it clearly in viewer. We will use this as viewer for maptiler's exports

**Comment by klokan** [comment]
Spec draft in: https://github.com/klokantech/tilejson-spec/tree/custom-projection/2.2.0

**Comment by petrsloup** [comment]
First adhoc version of the viewer (against latest stable ol3):
http://jsfiddle.net/L4psrp92/2/
The labs are missing CORS, so the CORS extension needs to be enabled for this to work.

I don't think it makes sense to try to PR this into stable ol3 unless we try to make this format more standardized.

To be discussed at the meeting (BTW the jsons linked above do not conform to the linked spec draft).

**Comment by klokan** [comment]
We need to be sure to test against official data sources:
- OSGB: https://github.com/klokan/maptiler/issues/569
- Swiss: https://github.com/klokan/maptiler/issues/570
- Baidu: https://github.com/klokan/maptiler/issues/459

**Comment by klokan** [comment]
@petrsloup - Baidu map example is available now, check https://github.com/klokan/maptiler/issues/459#issuecomment-215452633

This is pretty non-standard.
On OSGB/Swiss services are varying tile sizes and resolutions on different zoom levels - I can try to simulate this with multiple runs of maptiler and manual copying of rendered tiles and metadata.xml together. Is this required for the first TileJSON implementation?

**Comment by petrsloup** [comment]
Implemented in https://github.com/klokantech/tilejson-ol3. Additional tickets to be created there.
